#ifndef SYSTEMSETTINGS_GLOBAL_H
#define SYSTEMSETTINGS_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(SYSTEMSETTINGS_LIBRARY)
#  define SYSTEMSETTINGSSHARED_EXPORT Q_DECL_EXPORT
#else
#  define SYSTEMSETTINGSSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // SYSTEMSETTINGS_GLOBAL_H
